theme = "solarized-dark"
icons = "awesome"
 
[[block]]
block = "temperature"
 
[[block]]
block = "music"
max_width = 21
marquee = true
player = "spotify"
buttons = ["prev", "play", "next"]
 
[[block]]
block = "cpu"
interval = 0.7
 
[[block]]
block = "memory"
interval = 5
display_type = "memory"
info_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
 
[[block]]
block = "disk_space"
path = "/home/jmmiguel"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "custom"
interval = 1
cycle = ["iwgetid -r","hostname -i"]
#command = "hostname -i"

[[block]]
block = "sound"
interval = 3

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
 
[[block]]
block = "custom"
interval = 999999
command = "echo '\uF011'"
on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Reboot' 'reboot'"
